oldstr=str(input("enter any sentence : "))
a=str(input("enter the word which should be replaced : "))
b=str(input("enter the new word : "))
print("old string : ",oldstr)
newstr=oldstr.replace(a,b)
print("new string : ",newstr)